name: runTests

on:
  push:
  workflow_dispatch:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Run Tests
        run: |
          chmod +x ./gradlew
          ./gradlew test
