name: runTests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  gradle:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Run Tests
        run: ./gradlew test
